### ISSUE TITLE
ftdi-d2xx: The library has not been compiled for this architecture (Windows/AMD64). Run "cmake-js rebuild"

### ISSUE THREAD

**Issue by ArcherGu** [motla/ftdi-d2xx#1]
Sorry, I'm using electron and I can't use this addon on my system. win11 amd64

**Comment by motla** [comment]
One possible reason is that you run the addon in the renderer process, which has no access to Node.js. Did you read the [Note to Electron users](https://github.com/motla/ftdi-d2xx#note-to-electron-users)? And did you create a preload.js file to call this addon?

I should modify the code to print more accurate error messages.

**Comment by ArcherGu** [comment]
I run it in main process. And I even rebuild this on my computer, but still same error.

**Comment by motla** [comment]
Ok this is interesting 🤔  
Can you go to the `node_modules/ftdi-d2xx` folder and edit the main.js file to throw the actual error returned by the try/catch:
https://github.com/motla/ftdi-d2xx/compare/motla-patch-1
This will give us more information about the issue.

**Comment by ArcherGu** [comment]
Hi, I printed the exact error and it turned out to be a path problem. I was building electrons using espulud and I forgot to exclude native libraries from the build.

`external: ["ftdi-d2xx"]`

After modifying the configuration, everything is currently working fine, thank you very much for providing this native library.😀

**Comment by motla** [comment]
Cool! Enjoy. It's all new I just released it one month ago, I have no much user feedback yet so don't hesitate if you get issues.
