### ISSUE TITLE
Support FT_SetBitMode

### ISSUE THREAD

**Issue by kyleerik** [motla/ftdi-d2xx#3]
For my particular case I have to initialize the device by setting the bit mode and mask. This requires supporting the FT_SetBitMode function from the [D2XX library](https://www.ftdichip.com/Support/Documents/ProgramGuides/D2XX_Programmer's_Guide(FT_000071).pdf). 

I see that @ArcherGu prepared support for this. Is it complete? Tested? Are there plans for another release which includes it?

I also prepared changes to support just this one call. I have successfully tested my changes, and am willing to submit them, but I think those submitted by @ArcherGu are more extensive and complete.

I am willing to contribute time and effort necessary to help push these changes to a new release in NPM.

**Comment by motla** [comment]
Hi @kyleerik 

Thanks for your interest on this project!

Indeed, the code was written by @ArcherGu for `FT_SetBitMode` but I left it in the develop branch along some other improvements and I forgot to make a release 😬.

I'm sorry for that. I just released v1.2.0 which includes these updates:

- User can now open a device from its Description or USB location, in addition to its Serial Number.
- Support for `Device.setBitMode` thanks to @ArcherGu
- Support for `Device.setUSBParameters` and `Device.setLatencyTimer`
- Developer instructions in the README.md

**Comment by kyleerik** [comment]
Thank you so much! Merci beaucoup!
