### ISSUE TITLE
Error read in electron ver > 20.0.0

### ISSUE THREAD

**Issue by kr0n4ik** [motla/ftdi-d2xx#7]
Error - External buffers are not allowed (src\api\FTDI_Device_read.c:55) in electron ver ^20.0.0

**Comment by motla** [comment]
Hi @kr0n4ik,
Thanks for your interest on the library.

This is indeed a bug linked to newer versions of Electron.
Official Node-API documentation states:
> **[napi_create_external_arraybuffer](https://nodejs.org/api/n-api.html#napi_create_external_arraybuffer)**
> Some runtimes other than Node.js have dropped support for external buffers. On runtimes other than Node.js this method may return napi_no_external_buffers_allowed to indicate that external buffers are not supported. One such runtime is Electron as described in this issue [electron/issues/35801](https://github.com/electron/electron/issues/35801).

I will try to investigate what can be done, one idea could be to create the buffer in JavaScript and pass it as an argument to the read function. However I can't look at it before the end of September.

In the meantime you can get back to an older version of Electron, I believe <= 20.3.8 should work fine.

**Comment by robertbutz** [comment]
I am using electron and this library and got this error. Thank you for planning to look in to it.

**Comment by motla** [comment]
Hi guys, I made a patch v1.3.1 which fixes this issue. It should now work with the latest versions of Electron. Let me know if you still have issues.
