### ISSUE TITLE
Library executable not found for this architecture (Darwin/x64) - Run "cmake-js rebuild" from the ftdi-d2xx folder -- Error in old mac systems

### ISSUE THREAD

**Issue by nirhere** [motla/ftdi-d2xx#8]
Hello, 

I have an electron app that functions well in PC and new mac systems, connects to the cable functions well without any errors,
the mac installer for the app is compiled as --mac --universal but the library raises error in old mac systems, does the included driver supposed to support old mac systems ?

thanks

**Comment by motla** [comment]
Yes normally it should support ARM and Intel macs. Can you post the error?

**Comment by motla** [comment]
Oops sorry it was in the title. This is weird because regarding the error, the executable should be found on this line:

https://github.com/motla/ftdi-d2xx/blob/192ca0f010a07bf5463e754bd67fbd113ef21baa/main.js#L22

**Comment by motla** [comment]
Can you confirm `build/Release/ftdi-d2xx.Darwin.x86_64.node` exists inside the `ftdi-d2xx` folder?

**Comment by nirhere** [comment]
![error](https://github.com/user-attachments/assets/abafb3d2-3b17-4b5b-888c-c69d0cc64cab)

**Comment by nirhere** [comment]
> Can you confirm `build/Release/ftdi-d2xx.Darwin.x86_64.node` exists inside the `ftdi-d2xx` folder?

it does exist - I've used the electron universal option .. do you think that something is wrong with the electron compilation process ?

**Comment by motla** [comment]
I mean does it exist in the compiled application, not in your project. Regarding your console, the path would be `/Applications/sniff-...tdi-d2xx/build/Release/ftdi-d2xx.Darwin.x86_64.node`. The error suggests that the compilation process stripped away this file.
